
all:os-image.bin


os-image.bin: boot_sect.bin kernel.bin
	cat $^ > $@



run:os-image.bin
	qemu-system-i386 -fda os-image.bin



boot_sect.bin: boot_sect.asm
	nasm $< -f bin -o $@


entry.o : entry.asm	
	nasm $< -f elf -o  $@

kernel.o : kernel.c
	gcc -m32 -ffreestanding -c  $< -o $@

kernel.bin : entry.o kernel.o
	ld -m elf_i386  -o kernel.bin -Ttext 0x1000 entry.o kernel.o	--oformat binary

clean:
	rm *.bin *.o